image: maven:3.3.9-jdk-8
pipelines:
  default:
    - step:
        script: 
          - echo "The integration tests are run only on master branch"
          - mvn clean install -Pskip-int-tests 
          
  branches:
    master:
      - step:
          script:
          	- mvn --version
          	- echo "The integration tests are run only on master branch"
          	- mvn clean install